name: Weather Ingestion

on:
  schedule:
    - cron: "0 3,9,15 * * *"   # runs 3 times a day (3 AM, 9 AM, 3 PM UTC)
  workflow_dispatch:           # manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests boto3

      - name: Run ingestion
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: python scripts/ingest_weather.py

      
